apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ouiwokx59-python 
  janus-idp.io/tekton: ouiwokx59-python
  backstage.io/kubernetes-id: ouiwokx59-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ouiwokx59-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml