apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ouiwokx59-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ouiwokx59-python 
  name: ouiwokx59-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ouiwokx59-python 
